module DonationsHelper
  def required_image
    image_tag 'required.gif', :height => 15, :hspace => 3, :align => "texttop", :alt => "required", :width => 5
  end
  
  def card_types_for_select
    types = ActiveSupport::OrderedHash.new
    types['Visa'] = 'Visa'
    types['MasterCard'] = 'Mastercard'
    types['American Express'] = 'Amex'
    types['Discover'] = 'Discover'
    types
  end
  
  def states_for_select
    states = ActiveSupport::OrderedHash.new
    states['Select State'                  ]  = ''
    states['------'                        ]  = '' 
    states['Armed Forces of the Americas'  ]  = 'AA'
    states['Armed Forces Europe'           ]  = 'AE'
    states['Armed Forces Pacific'          ]  = 'AP'
    states[ '-----'                        ]  = ''
    states['Alabama'                       ]  = 'AL'
    states['Alaska'                        ]  = 'AK'
    states['American Samoa'                ]  = 'AS'
    states['Arizona'                       ]  = 'AZ'
    states['Arkansas'                      ]  = 'AR'
    states['California'                    ]  = 'CA'
    states['Colorado'                      ]  = 'CO'
    states['Connecticut'                   ]  = 'CT'
    states['Delaware'                      ]  = 'DE'
    states['District of Columbia'          ]  = 'DC'
    states['Federated States of Micronesia']  = 'FM'
    states['Florida'                       ]  = 'FL'
    states['Georgia'                       ]  = 'GA'
    states['Guam'                          ]  = 'GU'
    states['Hawaii'                        ]  = 'HI'
    states['Idaho'                         ]  = 'ID'
    states['Illinois'                      ]  = 'IL'
    states['Indiana'                       ]  = 'IN'
    states['Iowa'                          ]  = 'IA'
    states['Kansas'                        ]  = 'KS'
    states['Kentucky'                      ]  = 'KY'
    states['Louisiana'                     ]  = 'LA'
    states['Maine'                         ]  = 'ME'
    states['Marshall Islands'              ]  = 'MH'
    states['Maryland'                      ]  = 'MD'
    states['Massachusetts'                 ]  = 'MA'
    states['Michigan'                      ]  = 'MI'
    states['Minnesota'                     ]  = 'MN'
    states['Mississippi'                   ]  = 'MS'
    states['Missouri'                      ]  = 'MO'
    states['Montana'                       ]  = 'MT'
    states['Nebraska'                      ]  = 'NE'
    states['Nevada'                        ]  = 'NV'
    states['New Hampshire'                 ]  = 'NH'
    states['New Jersey'                    ]  = 'NJ'
    states['New Mexico'                    ]  = 'NM'
    states['New York'                      ]  = 'NY'
    states['North Carolina'                ]  = 'NC'
    states['North Dakota'                  ]  = 'ND'
    states['Northern Mariana Islands'      ]  = 'MP'
    states['Ohio'                          ]  = 'OH'
    states['Oklahoma'                      ]  = 'OK'
    states['Oregon'                        ]  = 'OR'
    states['Palau'                         ]  = 'PW'
    states['Pennsylvania'                  ]  = 'PA'
    states['Puerto Rico'                   ]  = 'PR'
    states['Rhode Island'                  ]  = 'RI'
    states['South Carolina'                ]  = 'SC'
    states['South Dakota'                  ]  = 'SD'
    states['Tennessee'                     ]  = 'TN'
    states['Texas'                         ]  = 'TX'
    states['Utah'                          ]  = 'UT'
    states['Vermont'                       ]  = 'VT'
    states['Virgin Islands'                ]  = 'VI'
    states['Virginia'                      ]  = 'VA'
    states['Washington'                    ]  = 'WA'
    states['West Virginia'                 ]  = 'WV'
    states['Wisconsin'                     ]  = 'WI'
    states['Wyoming'                       ]  = 'WY'
    states                         
  end                                             
end
